services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    env-file: 
     - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

volumes:
  mysql_data:
